### ISSUE TITLE
Surepy unlocking error

### ISSUE THREAD

**Issue by KernowSec** [benleb/surepy#47]
When trying to call the sevice for the cat flap to lock/unlock i get an unknown error. Looking at the logs outputs this:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 482, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1209, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 345, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 563, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/surepetcare/__init__.py", line 102, in handle_set_lock_state
    await spc.set_lock_state(call.data[ATTR_FLAP_ID], call.data[ATTR_LOCK_STATE])
  File "/usr/src/homeassistant/homeassistant/components/surepetcare/__init__.py", line 162, in set_lock_state
    await self.surepy.unlock(flap_id)
AttributeError: 'Surepy' object has no attribute 'unlock' ```

**Comment by benleb** [comment]
ah thanks! will fix this immediately 😳🤞

**Comment by benleb** [comment]
I mean, immediately after the macos update... 🙄🙄

**Comment by benleb** [comment]
ah, wait, that's wrong! you are using the "official" home assistant integration right? that will get the fix eventually, but *a little* later probably... the correct place to open an issue is here https://github.com/home-assistant/core/issues :)

if you are crazy enough, you can use the "dev" variant of the integration from here https://github.com/benleb/surepetcare
it's not stable or battle-tested or anything... but if there's a problem, I can fix it without relying on the home assistant release cycle. 

and, besides all that... this is the repository of the surepy python library which is not tied together with the integration.

for a quick&dirty fix, you can replace the broken method `set_lock_state` with this one (fixed version from https://github.com/benleb/surepetcare)

```python
    async def set_lock_state(self, flap_id: int, state: str) -> None:
        """Update the lock state of a flap."""

        # https://github.com/PyCQA/pylint/issues/2062
        # pylint: disable=no-member
        if state == LockState.UNLOCKED.name.lower():
            await self.surepy.sac.unlock(flap_id)
        elif state == LockState.LOCKED_IN.name.lower():
            await self.surepy.sac.lock_in(flap_id)
        elif state == LockState.LOCKED_OUT.name.lower():
            await self.surepy.sac.lock_out(flap_id)
        elif state == LockState.LOCKED_ALL.name.lower():
            await self.surepy.sac.lock(flap_id)
```
