### ISSUE TITLE
TypeError in Surepy

### ISSUE THREAD

**Issue by RogerSelwyn** [benleb/surepy#75]
I'm getting the following error using SuraHa v0.2.0 on HA 2021.9.2. I noticed the error after upgrading to a commit release from yesterday, then updated to 0.2 today hoping to resolve it. I currently have no cats registered to a single cat flap.

```
2021-09-05 08:19:36 ERROR (MainThread) [custom_components.sureha] Unexpected error fetching sureha_sensors data: object of type 'int' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/sureha/__init__.py", line 94, in async_update_data
return await spc.surepy.get_entities(refresh=True)
File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 389, in get_entities
await self.get_actions(household_id=household_id)
File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 169, in get_actions
await self.sac.call(method="GET", resource=resource) or {}
File "/usr/local/lib/python3.9/site-packages/surepy/client.py", line 284, in call
len(response_data.get("data", 0)),
TypeError: object of type 'int' has no len()
2021-09-05 08:19:36 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Sure Petcare' for sureha integration not ready yet: object of type 'int' has no len(); Retrying in background
```

Doing some debugging, it looks like you are trying to put out a debug message at line 284, which when it does the call to the below resource, returns nothing - maybe because I have added no cats yet:

`https://app.api.surehub.io/api/report/household/nnnnnn`

I'll write a pull request to handle.

**Comment by benleb** [comment]
fixed by #76, thanks!

will do a release this evening :)
